version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    command: ./bin/wait-for-postgres -- python manage.py runserver 0.0.0.0:8000
    env_file:
      - django.env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  gulp:
    build:
      context: .
      dockerfile: Dockerfile.gulp
    command: gulp
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - django

volumes:
  pgdata:
  node_modules:
